[project]
name = "module-01-docker-terraform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MathiWelz", email = "welzmathias@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.5.0",
    "ipywidgets>=8.1.9",
    "pandas>=3.0.6",
    "psycopg[binary,pool]>=3.3.6",
    "pyarrow>=25.0.1",
    "sqlalchemy>=2.1.4",
    "tqdm>=4.70.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pgcli>=4.7.1",
]
